### PR TITLE
Add link to Alchemy apps dashboard

### PR DESCRIPTION
**Pull request by pferreira101**
Why:

- Make it faster to setup the Alchemy API key.

How:

- On the `LiveBlockchainsStep`, add a link to the Alchemy Apps dashboard, where you can copy the API key.

Preview:
Screenshot 2023-10-20 at 15 07 51 (2)

### CODE REVIEW

**Comment by naps62** [comment]
can you include a screenshot of how the changes look?

**Review by naps62 — APPROVED** [review]

**Comment by naps62** [comment]
now that I see the screenshot, I find this solution a bit weird. Why is the link an icon next to the input? that makes it look like it would open whatever I write in there

The simple solution would be to just rearrange the copy and place the link somewhere in there. 

e.g.: instead of "Insert your API key below", we can change it to "Go to your [alchemy dashboard] and grab an API key"

**Comment by pferreira101** [comment]
> now that I see the screenshot, I find this solution a bit weird. Why is the link an icon next to the input? that makes it look like it would open whatever I write in there
> 
> The simple solution would be to just rearrange the copy and place the link somewhere in there.
> 
> e.g.: instead of "Insert your API key below", we can change it to "Go to your [alchemy dashboard] and grab an API key"

I removed the icon next to the input, it was a weird solution yeah. Should be better now.

**Comment by naps62** [comment]
@pferreira101 FYI I opened a PR with this branch directly to the main repo, made some changes and merged. so probably the easiest approach is to close this, and rebase `main` here against the upstream repo

**Pull request closed without merging**
